import { useState } from "react";
import { ArrowLeft, CheckCircle2, Eye, EyeOff, FlaskConical, KeyRound, Mail, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";
import { useFirebaseAuth } from "@/contexts/FirebaseAuthContext";
import { toast } from "sonner";
import { acceptEmailInput, sanitizePasswordInput } from "@/lib/accountValidation";

function AuthShell({ children, title, eyebrow, onBack }: { children: React.ReactNode; title: string; eyebrow: string; onBack?: () => void }) { return <div className="auth-shell"><div className="auth-brand"><div className="brand-mark"><FlaskConical size={21} /></div><div><strong>Medi<span>Dispense</span></strong><small>SECURE CONTROL CENTER</small></div></div><div className="auth-layout"><div className="auth-panel"><div className="auth-kicker">{eyebrow}</div><h1>{title}</h1>{children}</div><div className="auth-side"><ShieldCheck size={30} /><h2>Safe access for medicine operations.</h2><p>Only authorized staff can manage medicine records, inventory, machine status, and reports.</p><div className="auth-side-list"><span><CheckCircle2 size={15} /> Firebase email verification</span><span><CheckCircle2 size={15} /> Role-controlled admin access</span><span><CheckCircle2 size={15} /> Secure PHP session sync</span></div></div></div>{onBack ? <button className="auth-back" onClick={onBack}><ArrowLeft size={14} /> Back to sign in</button> : null}</div>; }
function PasswordField({ value, onChange, placeholder = "Password" }: { value: string; onChange: (value: string) => void; placeholder?: string }) { const [visible, setVisible] = useState(false); return <div className="auth-input-wrap"><KeyRound size={16} /><input type={visible ? "text" : "password"} value={value} onKeyDown={(e) => { if (/\s/.test(e.key) || /['"`;\\/<>]/.test(e.key)) e.preventDefault(); }} onChange={(e) => onChange(sanitizePasswordInput(e.target.value))} onPaste={(e) => { e.preventDefault(); onChange(sanitizePasswordInput(e.clipboardData.getData("text"))); }} maxLength={20} placeholder={placeholder} autoComplete="current-password" required /><button type="button" onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={15} /> : <Eye size={15} />}</button></div>; }
export default function Login() { const [, setLocation] = useLocation(); const auth = useFirebaseAuth(); const [mode, setMode] = useState<"login" | "reset">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { if (mode === "login") { await auth.signIn(email, password); toast.success("Signed in successfully"); setLocation("/"); } else { await auth.resetPassword(email); toast.success("Password reset link sent. Check your inbox."); setMode("login"); } } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Authentication failed."); } finally { setBusy(false); } };
  if (!auth.configured) return <AuthShell title="Firebase setup required" eyebrow="AUTHENTICATION NOT CONFIGURED"><p className="auth-copy">Add the VITE_FIREBASE_* variables to the frontend environment before using production sign-in.</p><div className="auth-config-note">Required: API key, Auth domain, Project ID, Storage bucket, Messaging sender ID, App ID.</div><button className="primary-button auth-submit" onClick={() => setLocation("/")}>Continue to preview</button></AuthShell>;
  if (mode === "reset") return <AuthShell title="Reset your password" eyebrow="ACCOUNT RECOVERY" onBack={() => setMode("login")}><form onSubmit={submit} className="auth-form"><label>Email address<div className="auth-input-wrap"><Mail size={16} /><input type="email" value={email} onKeyDown={(e) => { if (e.key === " ") e.preventDefault(); }} onChange={(e) => { const value = acceptEmailInput(e.target.value); if (value !== null) setEmail(value); }} maxLength={320} placeholder="admin@example.com" required /></div></label><p className="auth-copy">We will send a secure password reset link to your email address.</p><button className="primary-button auth-submit" disabled={busy}>{busy ? "Sending..." : "Send reset link"}</button></form></AuthShell>;
  return <AuthShell title="Welcome back." eyebrow="ADMIN SIGN IN"><form onSubmit={submit} className="auth-form"><label>Email address<div className="auth-input-wrap"><Mail size={16} /><input type="email" value={email} onKeyDown={(e) => { if (e.key === " ") e.preventDefault(); }} onChange={(e) => { const value = acceptEmailInput(e.target.value); if (value !== null) setEmail(value); }} maxLength={320} placeholder="admin@example.com" autoComplete="email" required /></div></label><label>Password<PasswordField value={password} onChange={setPassword} placeholder="Your password" /></label><button className="primary-button auth-submit" disabled={busy}>{busy ? "Please wait..." : "Sign in"}</button></form><div className="auth-links"><button onClick={() => setMode("reset")}>Forgot password?</button></div><div className="auth-footer-note">By continuing, you agree to use MediDispense only for authorized medicine vending operations.</div></AuthShell>; }
