import type { Alert, DashboardSummary, InventoryStatus, MachineStatus, Medicine, Transaction } from "@shared/medidispense";

const today = new Date();
const isoDays = (days: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
};
const nowIso = () => new Date().toISOString();
const deriveStatus = (quantity: number, minimum: number, expiryDate: string, enabled = true): InventoryStatus => {
  if (!enabled) return "out_of_stock";
  if (expiryDate < new Date().toISOString().slice(0, 10)) return "expired";
  if (expiryDate <= isoDays(30)) return "near_expiry";
  if (quantity === 0) return "out_of_stock";
  if (quantity <= minimum) return "low_stock";
  return "in_stock";
};

let medicines: Medicine[] = [
  { id: 1, name: "Paracetamol 500mg", genericName: "Paracetamol", category: "Pain Relief", description: "For temporary relief of minor aches and fever.", dosage: "Follow the dosage instructions shown on the medicine packaging or as directed by a healthcare professional.", instructions: "Take with water. Do not exceed the label directions.", stockQuantity: 42, minimumStockLevel: 10, price: 10, expiryDate: isoDays(210), imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=640&q=80", slotNumber: 1, status: "in_stock", enabled: true, dateAdded: "2026-08-18", updatedAt: nowIso() },
  { id: 2, name: "Cetirizine 10mg", genericName: "Cetirizine hydrochloride", category: "Allergy", description: "An antihistamine for temporary relief of common allergy symptoms.", dosage: "Use only as directed on the approved product label or by a healthcare professional.", instructions: "Read the label carefully before use.", stockQuantity: 18, minimumStockLevel: 8, price: 12, expiryDate: isoDays(90), imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=640&q=80", slotNumber: 2, status: "in_stock", enabled: true, dateAdded: "2026-08-20", updatedAt: nowIso() },
  { id: 3, name: "Vitamin C 500mg", genericName: "Ascorbic acid", category: "Vitamins", description: "A vitamin supplement configured for this machine.", dosage: "Follow the approved product label. Ask a pharmacist if you are unsure.", instructions: "Store in a cool, dry place.", stockQuantity: 7, minimumStockLevel: 8, price: 15, expiryDate: isoDays(24), imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=640&q=80", slotNumber: 3, status: "near_expiry", enabled: true, dateAdded: "2026-08-22", updatedAt: nowIso() },
  { id: 4, name: "Oral Rehydration Salts", genericName: "Oral rehydration solution", category: "Other OTC Medicines", description: "Electrolyte replacement product for the configured machine assortment.", dosage: "Follow the approved product label or consult a healthcare professional.", instructions: "Mix and use exactly as described on the packaging.", stockQuantity: 0, minimumStockLevel: 6, price: 18, expiryDate: isoDays(150), imageUrl: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=640&q=80", slotNumber: null, status: "out_of_stock", enabled: true, dateAdded: "2026-08-25", updatedAt: nowIso() },
  { id: 5, name: "Cold Relief Tablets", genericName: "Multi-symptom cold relief", category: "Cold and Flu", description: "Configured OTC cold relief product.", dosage: "Follow the dosage instructions on the approved product label.", instructions: "Do not combine with other products containing the same active ingredients.", stockQuantity: 4, minimumStockLevel: 5, price: 22, expiryDate: isoDays(-3), imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=640&q=80", slotNumber: null, status: "expired", enabled: true, dateAdded: "2026-08-27", updatedAt: nowIso() },
];

let transactions: Transaction[] = [
  { id: "TXN-000184", items: [{ medicineId: 1, medicineName: "Paracetamol 500mg", quantity: 1, unitPrice: 10, subtotal: 10 }], total: 10, amountPaid: 20, change: 10, paymentStatus: "successful", dispensingStatus: "dispensed", createdAt: new Date(Date.now() - 1000 * 60 * 23).toISOString(), slotNumber: 1 },
  { id: "TXN-000183", items: [{ medicineId: 2, medicineName: "Cetirizine 10mg", quantity: 2, unitPrice: 12, subtotal: 24 }], total: 24, amountPaid: 30, change: 6, paymentStatus: "successful", dispensingStatus: "dispensed", createdAt: new Date(Date.now() - 1000 * 60 * 77).toISOString(), slotNumber: 2 },
  { id: "TXN-000182", items: [{ medicineId: 3, medicineName: "Vitamin C 500mg", quantity: 1, unitPrice: 15, subtotal: 15 }], total: 15, amountPaid: 15, change: 0, paymentStatus: "successful", dispensingStatus: "failed", createdAt: new Date(Date.now() - 1000 * 60 * 122).toISOString(), slotNumber: 3 },
];
let nextMedicineId = 6;
let nextAlertId = 7;
let alerts: Alert[] = [
  { id: 1, kind: "low_stock", title: "Low stock", message: "Vitamin C 500mg has only 7 units remaining.", severity: "warning", createdAt: nowIso(), read: false },
  { id: 2, kind: "out_of_stock", title: "Out of stock", message: "Oral Rehydration Salts is unavailable for vending.", severity: "danger", createdAt: nowIso(), read: false },
  { id: 3, kind: "near_expiry", title: "Near expiry", message: "Vitamin C 500mg expires in 24 days.", severity: "warning", createdAt: nowIso(), read: false },
  { id: 4, kind: "expired", title: "Expired medicine", message: "Cold Relief Tablets has been removed from vending availability.", severity: "danger", createdAt: nowIso(), read: false },
  { id: 5, kind: "system", title: "Machine online", message: "MediDispense-01 is communicating normally.", severity: "info", createdAt: nowIso(), read: true },
];
let machine: MachineStatus = {
  machineName: "MediDispense-01", machineId: "MD-001", online: true, lastCommunication: nowIso(), esp32Status: "Ready", motorStatus: "Idle", sensorStatus: "Monitoring", coinAcceptorStatus: "Ready",
  slots: [1, 2, 3].map((slotNumber) => { const medicine = medicines.find((item) => item.slotNumber === slotNumber); return { slotNumber, medicineId: medicine?.id ?? null, medicineName: medicine?.name ?? null, motorId: `MOTOR-${slotNumber}`, sensorId: `IR-${slotNumber}`, quantity: medicine?.stockQuantity ?? 0, status: medicine ? medicine.stockQuantity === 0 ? "empty" : medicine.stockQuantity <= medicine.minimumStockLevel ? "low" : "ready" : "blocked", lastDispensingAt: null }; }),
};
const refreshStatuses = () => {
  medicines = medicines.map((medicine) => ({ ...medicine, status: deriveStatus(medicine.stockQuantity, medicine.minimumStockLevel, medicine.expiryDate, medicine.enabled), updatedAt: nowIso() }));
  machine.slots = machine.slots.map((slot) => { const medicine = medicines.find((item) => item.slotNumber === slot.slotNumber); return { ...slot, medicineId: medicine?.id ?? null, medicineName: medicine?.name ?? null, quantity: medicine?.stockQuantity ?? 0, status: medicine ? medicine.stockQuantity === 0 ? "empty" : medicine.stockQuantity <= medicine.minimumStockLevel ? "low" : "ready" : "blocked" }; });
};
const isToday = (value: string) => new Date(value).toDateString() === new Date().toDateString();

export const store = {
  listMedicines(includeUnavailable = true) { refreshStatuses(); return includeUnavailable ? medicines : medicines.filter((item) => item.enabled && item.slotNumber !== null && item.stockQuantity > 0 && item.status !== "expired"); },
  getMedicine(id: number) { refreshStatuses(); return medicines.find((medicine) => medicine.id === id); },
  createMedicine(input: Omit<Medicine, "id" | "status" | "dateAdded" | "updatedAt">) { const medicine: Medicine = { ...input, id: nextMedicineId++, status: deriveStatus(input.stockQuantity, input.minimumStockLevel, input.expiryDate, input.enabled), dateAdded: new Date().toISOString().slice(0, 10), updatedAt: nowIso() }; medicines = [medicine, ...medicines]; alerts = [{ id: nextAlertId++, kind: "system", title: "Medicine added", message: `${medicine.name} was added to the catalog.`, severity: "info", createdAt: nowIso(), read: false }, ...alerts]; refreshStatuses(); return medicine; },
  adjustStock(id: number, delta: number, reason: string) { const medicine = medicines.find((item) => item.id === id); if (!medicine) throw new Error("Medicine not found"); medicine.stockQuantity = Math.max(0, medicine.stockQuantity + delta); medicine.updatedAt = nowIso(); alerts = [{ id: nextAlertId++, kind: "system", title: "Inventory updated", message: `${medicine.name}: ${delta >= 0 ? "+" : ""}${delta} units (${reason}).`, severity: "info", createdAt: nowIso(), read: false }, ...alerts]; refreshStatuses(); return medicine; },
  summary(): DashboardSummary { refreshStatuses(); const sales = transactions.filter((txn) => txn.paymentStatus === "successful" && txn.dispensingStatus === "dispensed"); const categoryMap = new Map<string, number>(); medicines.forEach((medicine) => categoryMap.set(medicine.category, (categoryMap.get(medicine.category) ?? 0) + medicine.stockQuantity)); return { totalMedicines: medicines.length, totalStock: medicines.reduce((sum, item) => sum + item.stockQuantity, 0), lowStock: medicines.filter((item) => item.status === "low_stock").length, outOfStock: medicines.filter((item) => item.status === "out_of_stock").length, nearExpiry: medicines.filter((item) => item.status === "near_expiry").length, expired: medicines.filter((item) => item.status === "expired").length, todaysTransactions: sales.filter((txn) => isToday(txn.createdAt)).length, todaysSales: sales.filter((txn) => isToday(txn.createdAt)).reduce((sum, txn) => sum + txn.total, 0), pendingDispensing: transactions.filter((txn) => txn.dispensingStatus === "dispensing" || txn.dispensingStatus === "pending").length, salesTrend: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((label, index) => ({ label, value: [820, 1040, 760, 1320, 1180, 1640, 980][index] })), categoryMix: Array.from(categoryMap.entries()).map(([label, value]) => ({ label, value })) }; },
  listTransactions() { return [...transactions]; },
  listAlerts() { return alerts.slice(0, 8); },
  getMachine() { refreshStatuses(); return machine; },
  pingMachine() { machine.online = true; machine.lastCommunication = nowIso(); machine.esp32Status = "Ready"; return machine; },
  checkout(items: { medicineId: number; quantity: number }[]) { refreshStatuses(); const transactionItems = items.map((item) => { const medicine = medicines.find((candidate) => candidate.id === item.medicineId); if (!medicine || !medicine.enabled || medicine.stockQuantity < item.quantity || medicine.status === "expired" || medicine.status === "out_of_stock") throw new Error(`${medicine?.name ?? "Medicine"} is no longer available.`); return { medicineId: medicine.id, medicineName: medicine.name, quantity: item.quantity, unitPrice: medicine.price, subtotal: medicine.price * item.quantity }; }); const total = transactionItems.reduce((sum, item) => sum + item.subtotal, 0); const transaction: Transaction = { id: `TXN-${String(185 + transactions.length).padStart(6, "0")}`, items: transactionItems, total, amountPaid: 0, change: 0, paymentStatus: "pending", dispensingStatus: "pending", createdAt: nowIso(), slotNumber: medicines.find((item) => item.id === transactionItems[0]?.medicineId)?.slotNumber ?? null }; transactions = [transaction, ...transactions]; return transaction; },
  verifyPayment(id: string, amountPaid: number) { const transaction = transactions.find((item) => item.id === id); if (!transaction) throw new Error("Transaction not found"); if (amountPaid < transaction.total) throw new Error(`Payment is short by ₱${(transaction.total - amountPaid).toFixed(2)}.`); transaction.amountPaid = amountPaid; transaction.change = amountPaid - transaction.total; transaction.paymentStatus = "successful"; return transaction; },
  requestDispense(id: string) { const transaction = transactions.find((item) => item.id === id); if (!transaction || transaction.paymentStatus !== "successful") throw new Error("Payment must be verified before dispensing."); transaction.dispensingStatus = "dispensing"; machine.motorStatus = `Running ${transaction.slotNumber ? `MOTOR-${transaction.slotNumber}` : "motor"}`; machine.sensorStatus = "Waiting for IR confirmation"; return transaction; },
  verifyDispense(id: string, success: boolean) { const transaction = transactions.find((item) => item.id === id); if (!transaction || transaction.dispensingStatus !== "dispensing") throw new Error("No active dispensing request."); if (success) { transaction.dispensingStatus = "dispensed"; transaction.items.forEach((item) => { const medicine = medicines.find((candidate) => candidate.id === item.medicineId); if (medicine) medicine.stockQuantity = Math.max(0, medicine.stockQuantity - item.quantity); }); machine.motorStatus = "Idle"; machine.sensorStatus = "Monitoring"; const slot = machine.slots.find((item) => item.slotNumber === transaction.slotNumber); if (slot) slot.lastDispensingAt = nowIso(); refreshStatuses(); return transaction; } transaction.dispensingStatus = "failed"; machine.motorStatus = "Idle"; machine.sensorStatus = "Dispensing failure detected"; alerts = [{ id: nextAlertId++, kind: "dispensing_failure", title: "Dispensing failed", message: `${transaction.id} requires admin attention. Stock was not deducted.`, severity: "danger", createdAt: nowIso(), read: false }, ...alerts]; return transaction; },
  inventoryCsv() { refreshStatuses(); const header = "Medicine,Category,Quantity,Price,Expiry,Status,Slot\n"; return header + medicines.map((item) => [item.name, item.category, item.stockQuantity, item.price.toFixed(2), item.expiryDate, item.status, item.slotNumber ?? "Unassigned"].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); },
};
