import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { onAuthStateChanged, sendEmailVerification, sendPasswordResetEmail, signInWithEmailAndPassword, signOut, createUserWithEmailAndPassword, updateProfile, type User } from "firebase/auth";
import { apiBaseUrl, firebaseAuth, firebaseConfigured } from "@/firebase";

export type AppRole = "super_admin" | "admin" | "staff";
export type UserProfile = { id?: number; firebase_uid?: string; email?: string; display_name?: string; role_code?: AppRole; is_active?: boolean };
type AuthContextValue = { user: User | null; profile: UserProfile | null; loading: boolean; configured: boolean; error: string | null; signIn: (email: string, password: string) => Promise<void>; register: (name: string, email: string, password: string) => Promise<void>; resetPassword: (email: string) => Promise<void>; resendVerification: () => Promise<void>; logout: () => Promise<void>; refreshProfile: () => Promise<void> };
const AuthContext = createContext<AuthContextValue | null>(null);

function readableError(error: unknown) { const code = error instanceof Error ? error.message : "Authentication failed."; return code.replace("Firebase: ", "").replace(/\s*\(auth\/[^)]+\)\.?$/, ""); }

export function FirebaseAuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<User | null>(null); const [profile, setProfile] = useState<UserProfile | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const refreshProfile = async () => { if (!user) return; try { const token = await user.getIdToken(); if (!apiBaseUrl) { setProfile({ email: user.email ?? undefined, display_name: user.displayName ?? undefined, role_code: "staff" }); return; } const response = await fetch(`${apiBaseUrl}/api/auth/profile`, { method: "POST", credentials: "include", headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("Could not load the account profile."); const body = await response.json(); setProfile(body.data?.profile ?? null); } catch (caught) { setError(readableError(caught)); } };
  useEffect(() => { if (!firebaseAuth) { setLoading(false); return; } return onAuthStateChanged(firebaseAuth, async (nextUser) => { setUser(nextUser); setProfile(null); setError(null); if (nextUser) { try { const token = await nextUser.getIdToken(); sessionStorage.setItem("firebase-id-token", token); } catch {} } else sessionStorage.removeItem("firebase-id-token"); setLoading(false); }); }, []);
  useEffect(() => { if (user) void refreshProfile(); }, [user]);
  const value = useMemo<AuthContextValue>(() => ({ user, profile, loading, configured: firebaseConfigured, error, signIn: async (email, password) => { if (!firebaseAuth) throw new Error("Firebase is not configured."); setError(null); await signInWithEmailAndPassword(firebaseAuth, email.trim(), password); }, register: async (name, email, password) => { if (!firebaseAuth) throw new Error("Firebase is not configured."); setError(null); const result = await createUserWithEmailAndPassword(firebaseAuth, email.trim(), password); await updateProfile(result.user, { displayName: name.trim() }); await sendEmailVerification(result.user); }, resetPassword: async (email) => { if (!firebaseAuth) throw new Error("Firebase is not configured."); await sendPasswordResetEmail(firebaseAuth, email.trim()); }, resendVerification: async () => { if (!user) throw new Error("You are not signed in."); await sendEmailVerification(user); }, logout: async () => { const token = user ? await user.getIdToken().catch(() => "") : ""; if (apiBaseUrl) { await fetch(`${apiBaseUrl}/api/auth/logout`, { method: "POST", credentials: "include", headers: token ? { Authorization: `Bearer ${token}` } : undefined }).catch(() => undefined); } if (firebaseAuth) await signOut(firebaseAuth); sessionStorage.removeItem("firebase-id-token"); setProfile(null); }, refreshProfile }), [user, profile, loading, error]);
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
export function useFirebaseAuth() { const value = useContext(AuthContext); if (!value) throw new Error("useFirebaseAuth must be used inside FirebaseAuthProvider"); return value; }
